version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      DATABASE_URL: mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb
