export enum ResponseStatusCode {
  SUCCESS,
  NOT_FOUND,
  GET_AUTH_URL_ERROR,
  OAUTH_CODE_CALLBACK_ERROR,
  AUTH_ERROR,
  USER_NOT_FOUND,
  EDIT_USER_INFO_ERROR,
}

export enum HttpStatusCode {
  OK = 200,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}
