name: test
on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0.1
      - name: Install dependencies
        run: yarn install
      - name: Generate ECDSA keys
        run: |
          openssl ecparam -genkey -name secp256k1 -noout -out jwt_private_key.pem
          openssl ec -in jwt_private_key.pem -pubout -out jwt_public_key.pem
      - name: Test and generate coverage
        run: sudo yarn coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
